### ISSUE TITLE
Insufficient capabilities for change-dir-permissions init containers

### ISSUE THREAD

**Issue by cemery93** [netskopeoss/K8S-OpenShift-CloudExchange#4]
## The Problem

When using the `change-dir-permissions` init containers in a scenario where the following `securityContext` is applied
```yaml
securityContext:
  privileged: false
  allowPrivilegeEscalation: false
```

The resulting deployment, based on the corresponding template, is configured as
```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
  add:
    - CHOWN
    - FOWNER
  drop:
    - ALL
  privileged: false
```

Which results in the busybox containers within each pod that is configured to run the change-dir-permissions stage (which is achieved by setting
```yaml
volumePermissionContainer:
  create: true
```
in the initContainers block) being unable to execute their script containing the `chown` commands.

For example, when configured this way, the `core` deployment will crash due to these errors from the `change-dir-permissions` init container:
```
chown: /opt/netskope/plugins/custom_plugins: Operation not permitted
chown: /opt/netskope/plugins/: Operation not permitted
```

Similar issues are experienced with the RabbitMQ and MongoDB deployments, with their corresponding file paths in the error logs.

## The Solution

The fix for this is to add the following to the `securityContext` of each deployment:
```yaml
capabilities:
  drop:
    - ALL
  add:
    - CHOWN
    - FOWNER
```
The addition of `CHOWN` and `FOWNER` allows the busybox container to bypass file ownership warnings and modify the owner to the runtime user of the netskope deployments.

I have verified these changes locally, however I appear blocked from pushing a branch and creating a pull request for it on this repository. The above fix needs to be applied in the following locations:
- Line 85 of `templates/deployments/core-deployment.yaml`
- Line 83 of `templates/crds/mongodb.yaml`
- Line 104 of `templates/crds/mongodb.yaml` - this should become Line 107 once the first mongo fix is done
- Line 53 of `templates/crds/rabbitmq.yaml`

## Temporary Workaround

If anyone finds this and is experiencing the same issue, you can work around the issue by applying a patch with the config in the fix section to the resources listed above.
